# Generated by Django 4.1.2 on 2022-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('items', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('sales', models.TextField()),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('api_key', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('telegram_token', models.TextField(blank=True, default=None, null=True)),
                ('variables', models.TextField(default='{}')),
                ('items_json', models.TextField(default='[]')),
                ('notify_id', models.TextField(default='[]')),
            ],
        ),
    ]
